language: node_js
node_js:
  - 13

services:
  - docker
  
# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker-compose -f docker-compose-build.yaml build
  
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push svkll/udagram-api-user
  - docker push svkll/udagram-api-feed
  - docker push svkll/udagram-reverseproxy
  - docker push svkll/udagram-frontend
